2022-12-13 14:56:31,161 - d:/Gitlab/phy_cycle_test/server.py[line:1724] - INFO: Server Started
2022-12-13 15:00:28,668 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-05
2022-12-13 15:01:27,616 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:01:33,534 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:01:43,497 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:01:43,528 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:01:43,528 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:01:53,885 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:01:53,916 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:01:53,916 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:02:00,697 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:02:00,722 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:02:00,722 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:02:07,601 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:02:07,623 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:02:07,623 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:02:32,629 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:02:32,685 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:02:32,686 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:02:40,550 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:02:40,618 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:02:40,618 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:03:29,918 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:03:29,943 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:03:29,944 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:04:13,097 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:04:13,177 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:04:13,177 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:05:58,734 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:05:58,759 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:05:58,759 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:06:24,528 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:06:24,566 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:06:24,566 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:06:41,616 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:06:46,012 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:06:46,069 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:06:46,069 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:07:20,509 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:07:20,551 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:07:20,551 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:08:15,280 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:08:15,785 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:08:15,811 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:08:15,811 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:08:37,012 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:10:31,145 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:10:31,196 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:10:31,197 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:10:31,848 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:10:50,148 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults dypCQQRT,2022-12-13
2022-12-13 15:10:50,179 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 15:10:50,179 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: 4 is not in list
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1583, in get_db_search
    score_dic = self.get_pregnancy_score(result_json)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1602, in get_pregnancy_score
    o_index = list(dic.values()).index(4)
ValueError: 4 is not in list
2022-12-13 15:10:56,084 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:11:21,084 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:23:21,716 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:31:32,037 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 15:31:33,594 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 16:04:24,736 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 16:05:20,493 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 16:59:03,318 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:12:36,820 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:13:10,859 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:15:01,112 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:16:01,619 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:16:41,333 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:17:09,202 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults eDVXyLok,2022-12-13
2022-12-13 17:17:09,231 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 17:17:09,231 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: '>=' not supported between instances of 'int' and 'NoneType'
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1535, in get_db_search
    if data_diff >= men_cycle:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
2022-12-13 17:17:50,880 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:19:39,088 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:22:32,299 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults eDVXyLok,2022-12-13
2022-12-13 17:22:32,354 - d:/Gitlab/phy_cycle_test/server.py[line:1444] - INFO: PhySiologicalCycleStage error
2022-12-13 17:22:32,355 - d:/Gitlab/phy_cycle_test/server.py[line:1445] - ERROR: '>=' not supported between instances of 'int' and 'NoneType'
Traceback (most recent call last):
  File "d:/Gitlab/phy_cycle_test/server.py", line 1436, in PhySiologicalCycleStage
    json_str = self.get_db_search(ansql_test,uid,last_menstruation_date,menses_period,menses_duration)
  File "d:/Gitlab/phy_cycle_test/server.py", line 1535, in get_db_search
    if data_diff >= men_cycle:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
2022-12-13 17:44:30,783 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 17:45:11,139 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 18:14:01,105 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 18:14:33,896 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 18:14:41,223 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 18:15:31,695 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
2022-12-13 18:23:27,930 - d:/Gitlab/phy_cycle_test/server.py[line:1397] - INFO: PhyAllResults nF6TrofI,2022-12-13
